Resolving Checkov errors

diff --git a/.github/workflows/pr_builder.yaml b/.github/workflows/pr_builder.yaml
--- a/.github/workflows/pr_builder.yaml
+++ b/.github/workflows/pr_builder.yaml
@@ -2,55 +2,50 @@ name: pr-builder
 run-name: PR Builder
 on: pull_request
 
-
-jobs:
-  terraform-validate:
+permissions: read-all
+jobs:      
+  static-analysis-scanning:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v1
+    - uses: actions/checkout@master
+    - name: Checkov Scan
+      uses: bridgecrewio/checkov-action@v12
       with:
-        terraform_version: ${{ env.TF_VERSION }}
+        # This will add both a CLI output to the console and create a results.sarif file
+        output_format: cli,sarif
+        output_file_path: console,results.sarif
+      
+    # - name: Upload SARIF file
+    #   uses: github/codeql-action/upload-sarif@v2
+      
+    #   # Results are generated only on a success or failure
+    #   # this is required since GitHub by default won't run the next step
+    #   # when the previous one has failed. Security checks that do not pass will 'fail'.
+    #   # An alternative is to add `continue-on-error: true` to the previous step
+    #   # Or 'soft_fail: true' to checkov.
+    #   if: success() || failure()
+    #   with:
+    #     sarif_file: results.sarif
+  terraform-plan:
+    needs: static-analysis-scanning
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@master    
+    # Terraform Cloud Authentication
+    - uses: hashicorp/setup-terraform@v3
+    
     - name: Terraform Format
       run: terraform fmt -check
-    - name: Terraform Init
-      run: terraform init
-    - name: Terraform Validate
-      run: terraform validate
-      
-  security-scanning:
-    needs: terraform-validate
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-    - name: Checkov Scan
-      uses: bridgecrewio/checkov-action@master
-      with:
-        directory: ./terraform
-        soft_fail: false
-        framework: terraform
-    - name: Upload Checkov Results  
-      uses: actions/upload-artifact@v2
-      with:
-        name: checkov-report
-        path: checkov-report.json
-        
-  terraform-plan:
-    needs: security-scanning
-    runs-on: ubuntu-latest
-    steps:
     
-    # Terraform Cloud Authentication
-    - uses: hashicorp/terraform-cli@v1
     - name: Terraform Init
       run: terraform init
+    
     - name: Terraform Plan
       run: terraform plan -out=tfplan
       continue-on-error: true
+    
     - name: Upload TF Plan  
-      uses: actions/upload-artifact@v2
+      uses: actions/upload-artifact@v4
       with:
         name: tfplan
         path: tfplan
